{
 "title": "monitor2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Средняя задержка старта видео по регионам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(initial_playback_delay_ms_sum[1m])) by (region) / avg(rate(initial_playback_delay_ms_count[1m])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Общее количество событий старта воспроизведения по регионам и типам устройств",
   "type": "graph",
   "description": "Общее количество событий старта воспроизведения по регионам и типам устройств",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(initial_playback_delay_ms_count[5m])) by (region, device_type)",
     "legendFormat": "{{region}} - {{device_type}}"
    }
   ]
  },
  {
   "title": "Сравнение частоты ребуферингов между различными типами устройств",
   "type": "graph",
   "description": "Сравнение частоты ребуферингов между различными типами устройств",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rebuffer_count_total[1m])) by (device_type)",
     "legendFormat": "{{device_type}}"
    }
   ]
  },
  {
   "title": "Средняя продолжительность ребуферинга по регионам",
   "type": "gauge",
   "description": "Средняя продолжительность ребуферинга по регионам и типам устройств",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(total_stall_duration_ms_sum[1m])) by (region) / avg(rate(total_stall_duration_ms_count[1m])) by (region) / 1000",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Среднее время отклика CDN на пользователя по регионам",
   "type": "bargauge",
   "description": "Среднее время отклика CDN на пользователя по регионам",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cdn_response_time_ms_sum) by (region) / sum(cdn_response_time_ms_count) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}